### ISSUE TITLE
No button event on setting CP password after login

### ISSUE THREAD

**Issue by juliadin** [cryptpad/sso#9]
Hi,

i am running 2024.3.0 with the SSO plugin, registered an OpenID provider (running authentik 2024.4.2). Redirects and consent seem to work, but I am redirected to a page where I am asked to set a cp password. Regardless of what I enter or what I click, I can't set the password (the button seems to have no event bound).

This is the first time I am trying to setup SSO, I didn't come from a working setup upgrading or something.

I am using firefox to access cryptpad

Changing `cpPassword: true` doesn't change anything... 

Anonymized SSO config:

```javascript
//const fs = require('node:fs');
module.exports = {
    enabled: true,
    enforced: false,
    cpPassword: false,
    forceCpPassword: false,
    list: [
    {
        name: 'example-provider.id',
        type: 'oidc',
        url: 'https://id.example.com/application/o/example-cryptpad/',
        client_id: "...",
        client_secret: "...",
        jwt_alg: 'RS256'
    }
    ]
};
```

**Comment by davidbenque** [comment]
Hello and many thanks for your feedback. We have not been able to reproduce this problem. Please let us know which browser you are using and if any extensions from the [known issues list](https://docs.cryptpad.org/en/FAQ.html#common-issues) are active. Additionally any messages in the browser console (open with F12) could help us isolate the issue.

**Comment by juliadin** [comment]
thanks for your reply. I finally found the time to debug this. The problem was an extra slash in the SafeOrigin that led to the sso password form running from `https://my-domain//ssoauth` which led to the observed behavior. The rest of cryptpad seemed to deal fine with this.
There was no error in the console when i tried clicking the button nor was there any indication that there was a problem. Until I literally stubled upon the solution I was quite stumped :D

Thanks for helping me find this.
